on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Setup Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Login to GHCR
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Convert repo name to lowercase
      - name: Set Lowercase Variable
        run: echo "REPO_LOWER=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Show Variables
        run: |
          echo "Original: ${{ github.repository }}"
          echo "Lowercase: ${{ env.REPO_LOWER }}"

      # Build Image With Docker Composerun: 
      - name: Build images with Docker Compose
        run: |
          IMAGE_TAG=ghcr.io/${{ env.REPO_LOWER }}
          docker compose build \
            --build-arg IMAGE_TAG=$IMAGE_TAG \
            --build-arg GIT_SHA=${{ github.sha }}

      - name: Push images with Docker Compose
        run: docker compose push
        
      - name: List Docker Images
        run: docker images 
        
      # Security Scan with Trivy
      - name: Security Scan backend with Trivy
        uses: aquasecurity/trivy-action@0.16.1
        with:
          image-ref: ghcr.io/${{ env.REPO_LOWER }}/backend:latest{{ github.sha }}
          format: 'table'
          exit-code: '0' # set to 1 to fail on HIGH/CRITICAL
          vuln-type: 'os'
          severity: 'HIGH,CRITICAL'

      - name: Security Scan Frontend with Trivy
        uses: aquasecurity/trivy-action@0.16.1
        with:
          image-ref: ghcr.io/${{ env.REPO_LOWER }}/frontend:latest{{ github.sha }}
          format: 'table'
          exit-code: '0'
          vuln-type: 'os'
          severity: 'HIGH,CRITICAL'

      # Sign Image with Cosign
      - name: Sign Image with Cosign
        run: |
          cosign sign --key cosign.key ${{ env.IMAGE }}
