on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Setup Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Login to GHCR
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Convert repo name to lowercase
      - name: Set Lowercase Variable
        run: echo "REPO_LOWER=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Show Variables
        run: |
          echo "Original: ${{ github.repository }}"
          echo "Lowercase: ${{ env.REPO_LOWER }}"

      # Build & Push Image
      - name: Build & Push Backend
        run: |
          BACKEND_IMAGE=ghcr.io/${{ env.REPO_LOWER }}/backend:${{ github.sha }}
          echo "BACKEND_IMAGE=$BACKEND_IMAGE" >> $GITHUB_ENV
          docker build -t $BACKEND_IMAGE ./tasks-app/backend
          docker push $BACKEND_IMAGE

      - name: Build & Push Frontend
        run: |
          FRONTEND_IMAGE=ghcr.io/${{ env.REPO_LOWER }}/frontend:${{ github.sha }}
          echo "FRONTEND_IMAGE=$FRONTEND_IMAGE" >> $GITHUB_ENV
          docker build -t $FRONTEND_IMAGE ./tasks-app/frontend
          docker push $FRONTEND_IMAGE
      # Security Scan with Trivy
      - name: Security Scan with Trivy
        uses: aquasecurity/trivy-action@0.16.1
        with:
          image-ref: ${{ env.IMAGE }}
          format: 'table'
          exit-code: '0'

      # Sign Image with Cosign
      - name: Sign Image with Cosign
        run: |
          cosign sign --key cosign.key ${{ env.IMAGE }}
