name: Tasks_App CI/CD

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          uses: docker/login-action@v3
     
      
      - name: Set Lowercase Variable
        run: echo "REPO_LOWER=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
      - name: Use Lowercase Variable
        run: |
          echo "Original: ${{ github.repository }}"
          echo "Lowercase: ${{ env.REPO_LOWER }}"
        
      - name: Build and Push Image
          docker build -t $IMAGE ./app
          docker push $IMAGE

      - name: Security Scan with Trivy
        uses: aquasecurity/trivy-action@0.16.1
        with:
          image-ref: ghcr.io/${{ github.repository }}/app:${{ github.sha }}
          format: 'table'
          exit-code: '0' # fail if HIGH/CRITICAL → set to '1'

      - name: Sign Image with Cosign
        run: |
          echo "${{ secrets.COSIGN_PASSWORD }}" | cosign sign --key cosign.key ghcr.io/${{ github.repository }}/app:${{ github.sha }}

  
