name: Terraform CI/CD - Infra

on:
  push:
    # paths:
    #   - 'eks-infra/**'  # run only when infra folder changes
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Configure AWS credentials (OIDC or access keys)
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::117685249038:role/terrafor-role
          aws-region: us-east-2
          
          # Prefer OIDC with a role:
          # role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
       

      # Install Terraform CLI (setup-terraform)
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.5  # installs Terraform CLI [web:147][web:151]


      # Terraform Init (use -chdir and multiple backend-config lines)
      - name: Terraform Init
        run: |
          terraform -chdir=eks-infra init \
            -backend-config="bucket=${{ secrets.TF_S3_BUCKET }}" \
            -backend-config="key=${{ env.TF_WORKSPACE }}/terraform.tfstate" \
            -backend-config="region=${{ env.AWS_REGION }}" \
            -backend-config="dynamodb_table=${{ secrets.TF_DYNAMODB_LOCK_TABLE }}"
        # Tip: ensure no stray trailing spaces after backslashes to avoid arg parse issues [web:154][web:164][web:159]
   
      # Terraform Plan
      - name: Terraform Plan
        id: plan
        run: terraform -chdir=eks-infra plan -out=tfplan

      # Optional: upload plan file artifact
      - name: Upload plan artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: eks-infra/tfplan

      # Manual approval gate (use environment protection or a manual confirm)
      # If you truly want manual control, prefer GitHub Environments required reviewers.
      # Below is an example using workflow_dispatch plus a simple guard.
      - name: Await manual approval (environment gate)
        if: github.event_name == 'workflow_dispatch'
        uses: softprops/turnstyle@v2
        with:
          poll-interval-seconds: 10
        # Alternatively, use protected environment:
        # environment: production

      # Terraform Apply (only on manual dispatch)
      - name: Terraform Apply
        if: github.event_name == 'workflow_dispatch'
        run: terraform -chdir=eks-infra apply -auto-approve tfplan
